import {
	FaSpotify,
	FaHouseDamage,
	FaSearch,
	FaBookOpen,
	FaPlus,
	FaGlobe,
	FaChevronCircleLeft,
	FaChevronRight,
	FaChevronLeft,
} from "react-icons/fa";

import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Sidebar from "../components/Sidebar";

const poppins = Poppins({ subsets: ["latin"], weight: ["500", "600", "700"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<div className="flex bg-black min-h-screen p-[8px]">
					<Sidebar />
					<main className="flex-1 ml-[8px]">
						<header className="h-[64px] w-[100%] bg-[#121212] rounded-t-[8px]">
							<div className="navBar flex  flex-row items-center justify-between  ">
								<div className="navButton flex flex-row items-center gap-2 h-[64px] px-6">
									<div className="w-[30px] h-[30px] rounded-full bg-black flex items-center justify-center">
										<FaChevronLeft />
									</div>
									<div className="w-[30px] h-[30px] rounded-full bg-black flex items-center justify-center">
										<FaChevronRight />
									</div>
								</div>
								<div className="navButton flex flex-row items-center justify-end gap-2 h-[64px] px-6 ">
									<button className="  flex flex-row items-center justify-center px-[24px] py-[8px]">
										Sign up
									</button>
									<button className=" flex flex-row items-center justify-center  px-[24px] py-[8px] bg-[#fff] text-black rounded-[2rem]">
										Log in
									</button>
								</div>
							</div>
						</header>
						{children}
					</main>
				</div>
			</body>
		</html>
	);
}
